package com.hacknife.briefness;

import com.hacknife.briefness.util.FileUtil;
import com.hacknife.briefness.util.Logger;

import java.io.File;

public class ImmersiveInjector {
    public static final String PROMPY = "// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).\n" +
            "// If you have any questions in use, please use email to contact me (e-mail:4884280@qq.com).\n";
    public static final String CONTENT = "\n" +
            "import android.app.Activity;\n" +
            "import android.support.annotation.ColorRes;\n" +
            "import android.support.annotation.LayoutRes;\n"+
            "\n" +
            "public class ImmersiveInjector {\n" +
            "    public static int statusColor(Activity activity) {\n" +
            "        return com.hacknife.briefness.R.color.white;\n" +
            "    }\n" +
            "\n" +
            "    public static int navigationColor(Activity activity) {\n" +
            "        return com.hacknife.briefness.R.color.white;\n" +
            "    }\n" +
            "\n" +
            "    public static boolean statusEmbed(Activity activity) {\n" +
            "        return false;\n" +
            "    }\n" +
            "\n" +
            "    public static boolean navigationEmbed(Activity activity) {\n" +
            "        return false;\n" +
            "    }\n\n" +
            "    public static void setContentView(Activity activity, @LayoutRes int layout, @ColorRes int statusColor, @ColorRes int navigationColor, boolean statusEmbed, boolean navigationEmbed) {\n" +
            "    }\n" +
            "}\n";

    public void writeCode(String path, String packages) {
        if (!new File(path).exists()) {
            Logger.v(path);
            FileUtil.createFile(path, PROMPY + "package " + packages + ".briefness;\n" + CONTENT);
        }

    }
}
