package com.hacknife.briefness;

import com.hacknife.briefness.databinding.JavaLayout;
import com.hacknife.briefness.util.FileUtil;

import java.io.File;
import static com.hacknife.briefness.XmlParser.SPLIT;

/**
 * author  : Hacknife
 * e-mail  : 4884280@qq.com
 * github  : http://github.com/hacknife
 * project : Briefness
 */

public class JavaInjector {

    public static String PACKAGE(String packages) {
        return
                "// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).\n" +
                        "// If you have any questions in use, please use email to contact me (e-mail:4884280@qq.com).\n" +
                        "package " + packages + ";\n";
    }

    public static String IMPORT(String packages) {
        return "import android.graphics.Bitmap;\n" +
                "import android.util.Log;\n" +
                "import android.view.View;\n" +
                "import android.widget.Button;\n" +
                "import android.widget.EditText;\n" +
                "import android.widget.ImageView;\n" +
                "import android.widget.TextView;\n" +
                "import " + packages + ".briefness.ViewInjector;\n";
    }

    public static final String CLASS = "public class BriefnessInjector {\n" +
            "    public static void injector(View view, Object value) {\n" +
            "        if (value == null | view == null) {\n" +
            "        } else if (ViewInjector.injector(view, value)) {\n" +
            "        } else if (view instanceof ImageView) {\n" +
            "            injectImageView((ImageView) view, value);\n" +
            "        } else if (view instanceof Button) {\n" +
            "            injectButton((Button) view, value);\n" +
            "        } else if (view instanceof EditText) {\n" +
            "            injectEditText((EditText) view, value);\n" +
            "        } else if (view instanceof TextView) {\n" +
            "            injectTextView((TextView) view, value);\n" +
            "        } else {\n" +
            "            Log.e(\"Briefness\", \"No match method and can not inject \" + view.getClass().getSimpleName());\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "    private static void injectEditText(EditText view, Object value) {\n" +
            "        if (value instanceof String) {\n" +
            "            view.setText((String) value);\n" +
            "        } else if (value instanceof Integer) {\n" +
            "            view.setText((Integer) value);\n" +
            "        } else {\n" +
            "            Log.e(\"Briefness\", \"No match method and can not inject \" + view.getClass().getSimpleName());\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "\n" +
            "    private static void injectButton(Button view, Object value) {\n" +
            "        if (value instanceof String) {\n" +
            "            view.setText((String) value);\n" +
            "        } else if (value instanceof Integer) {\n" +
            "            view.setText((Integer) value);\n" +
            "        } else {\n" +
            "            Log.e(\"Briefness\", \"No match method and can not inject \" + view.getClass().getSimpleName());\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "    private static void injectImageView(ImageView view, Object value) {\n" +
            "        if (value instanceof Bitmap) {\n" +
            "            view.setImageBitmap((Bitmap) value);\n" +
            "        } else if (value instanceof Integer) {\n" +
            "            view.setImageResource((Integer) value);\n" +
            "        } else {\n" +
            "            Log.e(\"Briefness\", \"No match method and can not inject \" + view.getClass().getSimpleName());\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "    private static void injectTextView(TextView view, Object value) {\n" +
            "        if (value instanceof String) {\n" +
            "            view.setText((String) value);\n" +
            "        } else if (value instanceof Integer) {\n" +
            "            view.setText((Integer) value);\n" +
            "        } else {\n" +
            "            Log.e(\"Briefness\", \"No match method and can not inject \" + view.getClass().getSimpleName());\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "\n" +
            "}\n";

    public static String BRIEFNESS_INJECTOR(String modulePath) {
        return "// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).\n" +
                "// This class and method can not be confused and modified !!\n" +
                "package " + modulePath + ".briefness;\n" +
                "\n" +
                "import android.view.View;\n" +
                "\n" +
                "/**\n" +
                " * author  : Hacknife\n" +
                " * e-mail  : 4884280@qq.com\n" +
                " * github  : http://github.com/hacknife\n" +
                " * project : Briefness\n" +
                " */\n" +
                "public class ViewInjector {\n" +
                "    public static boolean injector(View view, Object value) {\n" +
                "        return false;\n" +
                "    }\n" +
                "}";
    }

    public void witeCode(String path, String packages) {

        String java = path + SPLIT
                + "src/main/java/"
                + packages.replace(".", "/")
                + "/briefness/ViewInjector.java";

        if (!new File(java).exists())
            FileUtil.createFile(java, BRIEFNESS_INJECTOR(packages));
    }


    public String getBriefnessInjectorCode(String path, String packages) {
        StringBuilder builder = new StringBuilder();
        return builder.append(PACKAGE(packages))
                .append(IMPORT(packages))
                .append(JavaLayout.author)
                .append(CLASS).toString();
    }
}
