// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).
// If you have any questions in use, please use email to contact me (e-mail:4884280@qq.com).
package com.hacknife.demo.briefness;

import android.app.Activity;
import android.support.annotation.ColorRes;
import android.support.annotation.LayoutRes;

public class ImmersiveInjector {
    public static int statusColor(Activity activity) {
        return com.hacknife.briefness.R.color.white;
    }

    public static int navigationColor(Activity activity) {
        return com.hacknife.briefness.R.color.white;
    }

    public static boolean statusEmbed(Activity activity) {
        return false;
    }

    public static boolean navigationEmbed(Activity activity) {
        return false;
    }

    public static void setContentView(Activity activity, @LayoutRes int layout, @ColorRes int statusColor, @ColorRes int navigationColor, boolean statusEmbed, boolean navigationEmbed) {
    }
}

