// Generated by BriefnessProcessor (https://github.com/hacknife/Briefness).
// This class and method can not be confused and modified !!
package com.hacknife.demo.briefness;

import android.view.View;

/**
 * author  : Hacknife
 * e-mail  : 4884280@qq.com
 * github  : http://github.com/hacknife
 * project : Briefness
 */
public class ViewInjector {
    public static boolean injector(View view, Object value) {
        return false;
    }
}
